[build]
  command = "npm run build"
  publish = "build" # For Create React App
  # publish = "dist" # For Vite

[[headers]]
  for = "/*"
  [headers.values]
    Content-Type = "application/javascript"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
